name: Upload catalog JSON to S3

on:
  push:
    branches:
      - main 
    paths:
      - packages/routing-edge/src/routes/frontend-catalog.json

jobs:
  env:
      S3_BUCKET_NAME: "arn:aws:s3:::us-east-1-856716035894-mfe-on-the-edge" 
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Upload HTML to S3
      run: |
        cd ./packages/routing-edge/src/routes
        aws s3 cp ./frontend-catalog.json s3://$S3_BUCKET_NAME/routes/