name: Upload catalog JSON to S3
run-name: 📖 ${{ github.actor }} is uploading JSON catalog 
on:
  push:
    branches:
      - main 
    paths:
      - 'packages/mfe-shell-spa/importmaps.json'
      - 'packages/routing-edge/src/routes/frontend-catalog.json'
      - '.github/workflows/front-end-catalog.yml'

jobs:
    shell:
        uses: "./.github/workflows/_reusable-uplad-file-s3.yml"
        with:
          file_to_upload: "packages/routing-edge/src/routes/frontend-catalog.json"
        secrets: inherit
    pokemon:
      uses: "./.github/workflows/_reusable-uplad-file-s3.yml"
      with:
        file_to_upload: "packages/mfe-shell-spa/importmaps.json"
      secrets: inherit